default_language_version:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
  golang: 1.24.6
=======
  golang: 1.24.5
>>>>>>> 9e457ac ([internal] update base images to v0.5.23 (#134))
=======
  golang: 1.24.6
>>>>>>> 892194d ([internal] fix CVE (#135))
=======
  golang: 1.24.4
>>>>>>> 6b5a2f8 ([controller] Make LocalStorageClass.spec.lvm.thick.contiguous nullable to preserve false on updates; add unit tests (#130))
repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.64.5
    hooks:
      - id: golangci-lint
        name: golangci-lint-ee
        entry: find -type f -name go.mod -execdir sh -c "golangci-lint run --new-from-rev HEAD --build-tags ee --fix --fast" {} +
      - id: golangci-lint
        name: golangci-lint-ce
        entry: find -type f -name go.mod -execdir sh -c "golangci-lint run --new-from-rev HEAD --build-tags ce --fix --fast" {} +
