default_language_version:
<<<<<<< HEAD
  golang: 1.24.6
=======
  golang: 1.24.5
>>>>>>> 9e457ac ([internal] update base images to v0.5.23 (#134))
repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.64.5
    hooks:
      - id: golangci-lint
        name: golangci-lint-ee
        entry: find -type f -name go.mod -execdir sh -c "golangci-lint run --new-from-rev HEAD --build-tags ee --fix --fast" {} +
      - id: golangci-lint
        name: golangci-lint-ce
        entry: find -type f -name go.mod -execdir sh -c "golangci-lint run --new-from-rev HEAD --build-tags ce --fix --fast" {} +
