---
apiVersion: v1
kind: Secret
metadata:
  name: d8-{{ .Chart.Name }}-controller-config
  namespace: d8-{{ .Chart.Name }}
type: Opaque
stringData:
  config: |-
    nodeSelector: {{ .Values.sdsLocalVolume.dataNodes.nodeSelector | toYaml | nindent 6 }}
