apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: localstorageclasses.storage.deckhouse.io
  labels:
    heritage: deckhouse
    module: sds-local-volume
    backup.deckhouse.io/cluster-config: "true"
spec:
  group: storage.deckhouse.io
  scope: Cluster
  names:
    plural: localstorageclasses
    singular: localstorageclass
    kind: LocalStorageClass
    shortNames:
      - lsc
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: |
            LocalStorageClass is a Kubernetes Custom Resource that defines a configuration for a Kubernetes StorageClass.
          required:
            - spec
          properties:
            spec:
              type: object
              description: |
                Defines a Kubernetes StorageClass configuration.
              required:
                - reclaimPolicy
                - volumeBindingMode
                - lvm
              properties:
                reclaimPolicy:
                  type: string
                  x-kubernetes-validations:
                    - rule: self == oldSelf
                      message: Value is immutable.
                  description: |
                    StorageClass reclaim policy. Possible values:

                    - `Delete`: If the PersistentVolumeClaim is deleted, the PersistentVolume and its associated storage are also deleted
                    - `Retain`: If the PersistentVolumeClaim is deleted, the PersistentVolume and its associated storage remain
                  enum:
                    - Delete
                    - Retain
                volumeBindingMode:
                  type: string
                  x-kubernetes-validations:
                    - rule: self == oldSelf
                      message: Value is immutable.
                  description: |
                    StorageClass binding mode. Possible values:

                    - `Immediate`: Creates a PersistentVolume immediately after the PersistentVolumeClaim is created
                    - `WaitForFirstConsumer`: Creates a PersistentVolume only after a Pod that uses the PersistentVolumeClaim is created
                  enum:
                    - Immediate
                    - WaitForFirstConsumer
                lvm:
                  type: object
                  description: |
                    LVM configuration.
                  required:
                    - type
                    - lvmVolumeGroups
                  x-kubernetes-validations:
                    - rule: |
                        (self.type == "Thin" && !has(self.thick)) || self.type != "Thin"
                      message: Field spec.lvm.thick is forbidden for Thin type.
                    - rule: |
                        (!has(self.thick) || !has(self.thick.contiguous) || (has(self.thick.contiguous) && self.thick.contiguous == oldSelf.thick.contiguous))
                      message: "Field 'contiguous' is immutable and cannot be added if not specified at creation."
                    - rule: |
                        (!has(oldSelf.thick) || has(self.thick) || !has(oldSelf.thick.contiguous))
                      message: "Field 'thick' cannot be removed if 'thick.contiguous' is specified."
                  properties:
                    type:
                      type: string
                      x-kubernetes-validations:
                        - rule: self == oldSelf
                          message: Value is immutable.
                      description: |
                        Provisioning type of the LVM Logical Volumes (LV) created for PersistentVolumes (PV).
                      enum:
                        - Thick
                        - Thin
                    thick:
                      type: object
                      x-kubernetes-validations:
                        - rule: |
                            (!has(oldSelf.contiguous) || has(self.contiguous))
                          message: "Field 'contiguous' cannot be removed."
                        - rule: |
                            (!has(self.contiguous) || (has(self.contiguous) && self.contiguous == oldSelf.contiguous))
                          message: Field 'contiguous' is immutable and cannot be added if not specified at creation.
                      description: |
                        Settings for Logical Volumes in a LVMVolumeGroup resource.
                      properties:
                        contiguous:
                          type: boolean
                          x-kubernetes-validations:
                            - rule: 'self == oldSelf'
                              message: Value is immutable.
                          description: |
                            If `true`, the Logical Volume will be created with the contiguous flag. 
                            
                            > Note: This flag should be used with caution because it may lead to poor scheduling of pods using the PersistentVolume. Our scheduler checks the free space in VG and selects nodes with the most free space for pods. However, it cannot determine the maximum amount of sequential free space available. Consequently, there may be situations where a pod is scheduled to a node, but the volume cannot be created due to insufficient contiguous free space. If such a situation arises, manual intervention will be required.
                    volumeCleanup:
                      type: string
                      enum: [RandomFillThreePass, RandomFillSinglePass, Discard]
                      description: |
                        Volume cleanup method after the PersistentVolume is deleted.
                        If this parameter is not set, there's no guarantee that the data will be completely deleted.

                        Allowed values:

                        - `RandomFillSinglePass`: The volume will be overwritten with random data once before deletion. This option is not recommended for solid-state drives (SSDs), as overwriting reduces the drive's lifespan.
                        - `RandomFillThreePass`: The volume will be overwritten with random data three times before deletion. This option is also not recommended for SSDs, as overwriting reduces the drive's lifespan.
                        - `Discard`: Before deletion, all blocks of the volume will be marked as free using the `discard` system call. This option is applicable only to SSDs.
                    lvmVolumeGroups:
                      type: array
                      description: |
                        List of LVMVolumeGroup resources where PersistentVolumes will be created.
                      items:
                        type: object
                        required:
                          - name
                        properties:
                          name:
                            type: string
                            description: |
                              LVMVolumeGroup resource name.
                          thin:
                            type: object
                            description: |
                              Thin pool in a LVMVolumeGroup resource.
                            required:
                              - poolName
                            properties:
                              poolName:
                                type: string
                                description: |
                                  Thin pool name.
                                minLength: 1
                                pattern: ^.*$
                fsType:
                  type: string
                  default: ext4
                  x-kubernetes-validations:
                    - rule: self == oldSelf
                      message: Value is immutable.
                  description: |
                    StorageClass file system type.
                  enum:
                    - ext4
                    - xfs
            status:
              type: object
              description: |
                Current state of the StorageClass.
              properties:
                phase:
                  type: string
                  description: |
                    StorageClass current state. Possible values:

                    - `Failed`: The controller received incorrect resource configuration or errors occurred during the operation
                    - `Created`: All operations completed successfully
                  enum:
                    - Failed
                    - Created
                reason:
                  type: string
                  description: |
                    Additional information about the current state of the StorageClass.
      additionalPrinterColumns:
        - jsonPath: .status.phase
          name: Phase
          type: string
        - jsonPath: .status.reason
          name: Reason
          type: string
          priority: 1
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
          description: The age of this resource
