{
 "title": "Go Processes",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "2024-07-22T04:07:25.498Z", "to": "2024-07-22T12:47:31.395Z" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Go memstats alloc rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(go_memstats_sys_bytes{job=~\"sds.*\"}[$__rate_interval])",
     "legendFormat": "{{job}} ({{node}}) - bytes sys"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"sds.*\"}[$__rate_interval])",
     "legendFormat": "{{job}} ({{node}}) - bytes_total"
    },
    {
     "expr": "rate(go_memstats_heap_alloc_bytes{job=~\"sds.*\"}[$__rate_interval])",
     "legendFormat": "{{job}} ({{node}}) - heap alloc"
    }
   ]
  },
  {
   "title": "go threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "go_threads{job=~\"sds.*\"}",
     "legendFormat": "{{app}} ({{node}}) "
    }
   ]
  },
  {
   "title": "Process open fds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "process_open_fds{job=~\"sds.*\"}",
     "legendFormat": "{{job}} ({{node}})"
    }
   ]
  },
  {
   "title": "Process memory bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_resident_memory_bytes{job=~\"sds.*\"}[$__rate_interval])) by (app, node)",
     "legendFormat": "{{app}} ({{node}}) - resident"
    },
    {
     "expr": "sum(rate(process_virtual_memory_bytes{job=~\"sds.*\"}[$__rate_interval])) by (app, node)",
     "legendFormat": "{{app}} ({{node}}) - virtual"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=~\"sds.*\"}",
     "legendFormat": "{{app}} ({{node}})"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{job=~\"sds.*\"}[$__rate_interval])",
     "legendFormat": "{{app}}: {{node}}"
    }
   ]
  }
 ]
}