apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: local.csi.storage.deckhouse.io
  labels:
    heritage: deckhouse
    module: storage
spec:
  attachRequired: true
  podInfoOnMount: false
